### ISSUE TITLE
Options menu?

### ISSUE THREAD

**Issue by phaolo2** [jscher2000/dont-accept-webp#2]
Could you please add an Options tab or menu in the extension page?
So I won't need to keep the icon in the already-crowded toolbar for it.
Thank you.

**Comment by jscher2000** [comment]
Hi, I suggest moving the icon to the overflow menu for two-click access. Here's how:

right-click the toolbar button > Pin to Overflow Menu

![Fx96-extension-button-pin-overflow](https://user-images.githubusercontent.com/8264646/146504473-9a711baa-49d7-4ea5-8bed-832b39d92526.png)

Would that work for you?
