### ISSUE TITLE
Whitelist option?

### ISSUE THREAD

**Issue by modelfe** [jscher2000/dont-accept-webp#3]
I just found that this extension is causing a "You have been blocked" message on the Patreon login page - https://www.patreon.com/login - which I can't get around without disabling the extension.

Can you please add a whitelist or "exclude domain" option?

Thanks for maintaining this extension!

**Comment by jscher2000** [comment]
I just submitted a version 0.8 with an exemption for Patreon (another user mentioned this problem 6 days ago so it was in the works). Please let me know whether it works for you.

I still don't understand why it's needed...

**Comment by Murbek** [comment]
I originally blocked webp in the about:config Firefox settings, but this blocked thumbnails on youtube for some reason, which was incredibly frustrating.

Then I tried this extension, and the whitelist option works great, so thanks so much. :)

**Comment by billkewl** [comment]
How to exempt a url with path in it? like only exclude `example.com/path1` ?
Aslo is it possible to manually edit whitelist?
