### ISSUE TITLE
Please make this for Google Chrome as well!

### ISSUE THREAD

**Issue by PhilHubNew2022** [jscher2000/dont-accept-webp#8]
Google Chrome doesn't have this add-on yet!

**Comment by jscher2000** [comment]
I don't think the Chrome store is accepting new Manifest v2 extensions, so it's probably too late for a straight port. Someone needs to rewrite this extension using the declarativeNetRequest API. It sounds possible, but I don't have any experience using it. Also, I don't know how the exclusion list would work (recently added feature).

Perhaps for now you can set up a header edit through a more general purpose add-on like this one: https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj -- I have not tried it myself.

**Comment by PhilHubNew2022** [comment]
I am no programmer idiot. Just suggesting that YOU should make this for Chrome! but I guess you think Chrome is not your type of browser like most other people using it. Fire Fox is getting overrated and Chrome is not because Google is screwing up business nowadays. Well, sooner or later once Fire Fox runs out of business I don't know what else you should do or where your repo should be made for if you are going to refuse making your app more open with other browsers. 

Webp should be considered a criminal format and shouldn't have exist to annoy the hell out of us for trying to download images! I think it was just made to prevent people from using images for stupid copyright laws. :/ 

You are not supporting people here if you are not going to make this very handy app more open to other browsers besides only overrated Fire Fox.

**Comment by jscher2000** [comment]
> I am no programmer idiot. 

I didn't say you were either a programmer or an idiot. Google disabled the method this add-on uses to modify requests to websites. If you've seen articles about how some ad blockers don't work any more, it's the same problem. So this add-on cannot run in Chrome. Someone will need to write a new one using the new method.
